version: "3"
services:
  app:
    restart: always
    build: .
    container_name: "dl_audio_app"
    working_dir: "/root/"
    tty: true
    volumes:
      - ./src:/root/src
      # - ./lib:/pip-lib
