version: "3"
services:
  pytorch_test:
    restart: always
    build: .
    container_name: "pytorch_test"
    working_dir: "/root/"
    tty: true
    volumes:
      - ./src:/root/src
      - ./lib:/pip-lib
    environment:
      PYTHONPATH: /pip-lib
