version: "3"
services:
  auido_data_augment:
    restart: always
    build: .
    container_name: "auido_data_augment"
    working_dir: "/root/"
    tty: true
    volumes:
      - ./src:/root/src
    environment:
      PYTHONPATH: /pip-lib
