version: "3"
services:
  jupyter_module:
    restart: always
    build: .
    container_name: "study_asp"
    working_dir: "/root/work"
    tty: true
    volumes:
      - .:/root/work
    ports:
      - 8888:8888
# ブラウザ上で開く方法
# $ pip install jupyter jupyterlab
# $ jupyter notebook --port 8888 --ip=0.0.0.0 --allow-root
# https://qiita.com/shizuma/items/a4738c5a250ddc6d0c9f